import type { Restaurant, MenuItem, User, Order } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "john@example.com",
    name: "John Doe",
    phone: "+1234567890",
    address: "123 Main St, City, State 12345",
    createdAt: new Date("2024-01-15"),
  },
]

export const mockRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "Pizza Palace",
    description: "Authentic Italian pizzas made with fresh ingredients",
    image: "/pizza-restaurant-storefront.jpg",
    cuisine: "Italian",
    rating: 4.5,
    deliveryTime: "25-35 min",
    deliveryFee: 2.99,
    minimumOrder: 15.0,
    isOpen: true,
    address: "456 Pizza Ave, City, State",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Burger Barn",
    description: "Juicy burgers and crispy fries made to order",
    image: "/burger-restaurant-storefront.png",
    cuisine: "American",
    rating: 4.2,
    deliveryTime: "20-30 min",
    deliveryFee: 1.99,
    minimumOrder: 12.0,
    isOpen: true,
    address: "789 Burger Blvd, City, State",
    createdAt: new Date("2024-01-02"),
  },
  {
    id: "3",
    name: "Sushi Zen",
    description: "Fresh sushi and Japanese cuisine",
    image: "/sushi-restaurant-storefront.jpg",
    cuisine: "Japanese",
    rating: 4.7,
    deliveryTime: "30-40 min",
    deliveryFee: 3.99,
    minimumOrder: 20.0,
    isOpen: true,
    address: "321 Sushi St, City, State",
    createdAt: new Date("2024-01-03"),
  },
  {
    id: "4",
    name: "Taco Fiesta",
    description: "Authentic Mexican tacos and burritos",
    image: "/mexican-restaurant-storefront.jpg",
    cuisine: "Mexican",
    rating: 4.3,
    deliveryTime: "15-25 min",
    deliveryFee: 1.49,
    minimumOrder: 10.0,
    isOpen: false,
    address: "654 Taco Trail, City, State",
    createdAt: new Date("2024-01-04"),
  },
]

export const mockMenuItems: MenuItem[] = [
  // Pizza Palace items
  {
    id: "1",
    restaurantId: "1",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and fresh basil",
    price: 16.99,
    image: "/margherita-pizza.png",
    category: "Pizza",
    isAvailable: true,
    ingredients: ["Tomato sauce", "Mozzarella", "Fresh basil", "Olive oil"],
  },
  {
    id: "2",
    restaurantId: "1",
    name: "Pepperoni Pizza",
    description: "Traditional pizza with pepperoni and mozzarella cheese",
    price: 18.99,
    image: "/pepperoni-pizza.png",
    category: "Pizza",
    isAvailable: true,
    ingredients: ["Tomato sauce", "Mozzarella", "Pepperoni"],
  },
  // Burger Barn items
  {
    id: "3",
    restaurantId: "2",
    name: "Classic Cheeseburger",
    description: "Beef patty with cheese, lettuce, tomato, and special sauce",
    price: 12.99,
    image: "/classic-cheeseburger.png",
    category: "Burgers",
    isAvailable: true,
    ingredients: ["Beef patty", "Cheese", "Lettuce", "Tomato", "Special sauce", "Bun"],
  },
  {
    id: "4",
    restaurantId: "2",
    name: "Crispy Fries",
    description: "Golden crispy french fries with sea salt",
    price: 4.99,
    image: "/crispy-french-fries.png",
    category: "Sides",
    isAvailable: true,
    ingredients: ["Potatoes", "Sea salt"],
  },
  // Sushi Zen items
  {
    id: "5",
    restaurantId: "3",
    name: "California Roll",
    description: "Crab, avocado, and cucumber roll with sesame seeds",
    price: 8.99,
    image: "/california-sushi-roll.jpg",
    category: "Rolls",
    isAvailable: true,
    ingredients: ["Crab", "Avocado", "Cucumber", "Nori", "Rice", "Sesame seeds"],
  },
  {
    id: "6",
    restaurantId: "3",
    name: "Salmon Nigiri",
    description: "Fresh salmon over seasoned sushi rice",
    price: 6.99,
    image: "/salmon-nigiri-sushi.jpg",
    category: "Nigiri",
    isAvailable: true,
    ingredients: ["Fresh salmon", "Sushi rice"],
  },
  // Taco Fiesta items
  {
    id: "7",
    restaurantId: "4",
    name: "Chicken Tacos",
    description: "Grilled chicken with onions, cilantro, and lime",
    price: 9.99,
    image: "/chicken-tacos-mexican.jpg",
    category: "Tacos",
    isAvailable: true,
    ingredients: ["Grilled chicken", "Onions", "Cilantro", "Lime", "Corn tortilla"],
  },
  {
    id: "8",
    restaurantId: "4",
    name: "Beef Burrito",
    description: "Seasoned beef with rice, beans, cheese, and salsa",
    price: 11.99,
    image: "/beef-burrito-mexican.jpg",
    category: "Burritos",
    isAvailable: true,
    ingredients: ["Seasoned beef", "Rice", "Black beans", "Cheese", "Salsa", "Flour tortilla"],
  },
]

export const mockOrders: Order[] = [
  {
    id: "1",
    userId: "1",
    restaurantId: "1",
    items: [
      {
        menuItemId: "1",
        quantity: 1,
        price: 16.99,
      },
      {
        menuItemId: "2",
        quantity: 1,
        price: 18.99,
      },
    ],
    status: "delivered",
    totalAmount: 38.97,
    deliveryAddress: "123 Main St, City, State 12345",
    orderDate: new Date("2024-01-20"),
    estimatedDeliveryTime: new Date("2024-01-20T19:30:00"),
    actualDeliveryTime: new Date("2024-01-20T19:25:00"),
  },
]
